spring:
  application:
    name: stadium-service



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19097
